apiVersion: v1
kind: Service
metadata:
  name: marketplace
spec:
    type: NodePort
    selector:
        app: marketplace
    ports:
        - port: 5000
          targetPort: 5000
          protocol: TCP
